name: Deploy

on:
  push:
    branches:
      - master  # Deploy only on master branch
    tags:
      - v0.*    # Deploy for v0.* tags
      - v1.*    # Deploy for v1.* tags

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Login to Google Cloud
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        uses: actions/gcloud/auth@master
      - name: Kill process
        uses: actions/gcloud/cli@master
        with:
          args: compute --project "personal-website-236609" -q --account "bogdan.floris@gmail.com" ssh "personal-website" --zone "us-east1-b" --command "ls"
